[package]
name = "abm"
version = "0.0.1"
authors = ["Alessia Antelmi <aantelmi@unisa.it>","Matteo D'Auria <matdauria@unisa.it>","Daniele De Vinco <danieledevinco1996@gmail.com", "Carmine Spagnuolo <spagnuolocarmine@gmail.com>"]
edition = "2019"
license = "MIT"
keywords = ["discrete", "simulation","agent based model","agent based simulation"]
categories = ["science", "simulation","agent based model"]
readme = "README.md"
homepage = "https://github.com/spagnuolocarmine/abm"
repository = "https://github.com/spagnuolocarmine/abm"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3

[dependencies]
hashbrown = "0.3"
priority-queue = "0.5.4"
criterion = "0.1.2"
rand = "0.6.5"
lazy_static = "1.3.0"
piston_window = "0.81.0"
piston = "0.48.0"
piston2d-graphics = "0.32.0"
pistoncore-glutin_window = "0.61.0"
piston2d-opengl_graphics = "0.65.0"

[[bench]]
name = "benchmark"
harness = false

[[bin]]
name = "boids"
path = "examples/boids.rs"
