[package]
name = "abm"
version = "0.1.0"
authors = ["Daniele De Vinco <danieledevinco1996@gmail.com", "Carmine Spagnuolo <spagnuolocarmine@gmail.com>"]
edition = "2018"
keywords = ["discrete", "simulation","agent based model","agent based simulation"]
categories = ["science", "simulation","agent based model"]

[profile.dev]
opt-level = 3

[dependencies]
priority-queue = "0.5.4"
criterion = "0.1.2"
rand = "0.6.5"
lazy_static = "1.3.0"
piston_window = "0.81.0"

[[bench]]
name = "benchmark"
harness = false

[[bin]]
name = "boids"
path = "examples/boids_ui.rs"

[profile.release]
 debug = true
